---
- hosts: Windows
  
  tasks:

    - name: Disable task event 
      win_scheduled_task:
        name: Firewall_disable
        path: \
        state: absent

    - name: Reactivating Windows Firewall and Default Rules
      win_firewall:
        state: enabled
        profiles:
          - Domain
          - Private
          - Public
    
    - name: Re-create the task to monitor Firewall
      win_scheduled_task:
        name: Firewall_disable
        triggers: 
          - type: event
            subscription:  <QueryList><Query Id="0" Path="Microsoft-Windows-Windows Firewall With Advanced Security/Firewall"><Select Path="Microsoft-Windows-Windows Firewall With Advanced Security/Firewall">*[System[(EventID=2003)]]</Select></Query></QueryList>
        actions:
          - path: C:\Users\Administrator\Documents\callback.bat   
        username: Administrator
        state: present
        tags: create_event

  #- name: Create incident
  #    servicenow.itsm.incident:
  #     instance:
   #     host: https://{{ SN_INSTANCE }}.service-now.com/
   #     username: "{{ SN_USERNAME }}"
   #     password: "{{ SN_PASSWORD }}"

   #    state: new
   #    caller: admin
   #    short_description: System Remediation limit hit. Severity High - Nuno Help us!
  #     description: node01.nostromo.co.za is in a critical condition. Remediation attempts have hit level 5 n/ {{ aide_results }}
  #     attachments:
  #      - path: /tmp/aide.txt
  #     urgency: high
  #     impact: high
