---
- hosts: Windows
  collections:
    - servicenow.itsm
    
  tasks:

    - name: Disable task event 
      win_scheduled_task:
        name: Firewall_disable
        path: \
        state: absent

    - name: Reactivating Windows Firewall and Default Rules
      win_firewall:
        state: enabled
        profiles:
          - Domain
          - Private
          - Public
    
    - name: Re-create the task to monitor Firewall
      win_scheduled_task:
        name: Firewall_disable
        triggers: 
          - type: event
            subscription:  <QueryList><Query Id="0" Path="Microsoft-Windows-Windows Firewall With Advanced Security/Firewall"><Select Path="Microsoft-Windows-Windows Firewall With Advanced Security/Firewall">*[System[(EventID=2003)]]</Select></Query></QueryList>
        actions:
          - path: C:\Users\Administrator\Documents\callback.bat   
        username: Administrator
        state: present
        tags: create_event

    - name: Create incident
      servicenow.itsm.incident:
        state: new
        caller: "{{ lookup('env', 'SN_USERNAME') }}"
        short_description: "Windows Node is out of compliance"
        description: "Compliance failure. Attempted change on a compliance item on windows_node01 - Controller has re-applied the policy configuration"
        impact: high
        urgency: high
      register: new_incident
      delegate_to: localhost

    - set_fact:
        incident_number_cached: "{{ new_incident.record.number }}"
        cacheable: true

    - debug:

        # Use the output of the incident creation task to display the incident number
        msg: "This remediation was logged: {{ new_incident.record.number }}"
