---
- hosts: Windows
  collections:
    - servicenow.itsm
  vars:
    SN_INSTANCE:
    SN_USERNAME:
    SN_PASSWORD:
    
  
  tasks:

    - name: Disable task event 
      win_scheduled_task:
        name: Firewall_disable
        path: \
        state: absent

    - name: Reactivating Windows Firewall and Default Rules
      win_firewall:
        state: enabled
        profiles:
          - Domain
          - Private
          - Public
    
    - name: Re-create the task to monitor Firewall
      win_scheduled_task:
        name: Firewall_disable
        triggers: 
          - type: event
            subscription:  <QueryList><Query Id="0" Path="Microsoft-Windows-Windows Firewall With Advanced Security/Firewall"><Select Path="Microsoft-Windows-Windows Firewall With Advanced Security/Firewall">*[System[(EventID=2003)]]</Select></Query></QueryList>
        actions:
          - path: C:\Users\Administrator\Documents\callback.bat   
        username: Administrator
        state: present
        tags: create_event

    - name: print vars
      debug:
        msg: {{ SN_INSTANCE }}

   # - name: Create incident
     # servicenow.itsm.incident:
    #   instance:
   #     host: "https://{{ SN_INSTANCE }}.service-now.com/"
  #      username: "{{ SN_USERNAME }}"
 #       password: "{{ SN_PASSWORD }}"
#       state: new
#       caller: admin
#       short_description: Firewall Compliance Failure on Node
#       description: Node impacted by compliance policy failure on Firewall Settings
#       urgency: high
#       impact: high
