- hosts: Windows

  tasks:

     - name: Checking system against CIS 2022 Server Baselines
       block:
         - name: Checking system against CIS 2022 Server Baselines
           win_firewall:
             state: enabled
             profiles:
               - Domain
               - Private
               - Public
